api-version: "1.21"
name: FirEnchantKt
version: ${version}
main: top.catnies.firenchantkt.FirEnchantPlugin
loader: top.catnies.firenchantkt.FirEnchantPluginLoader
#bootstrapper:
#load: POSTWORLD
authors:
  - Catnies
  - ChengZhiMeow
folia-supported: true
dependencies:
  server:
    # 强依赖插件
    PlaceholderAPI: {load: BEFORE, required: true, join-classpath: true}

    # 物品依赖插件
    Nexo: { load: BEFORE, required: false, join-classpath: true }
    Oraxen: { load: BEFORE, required: false, join-classpath: true }
    Itemsadder: { load: BEFORE, required: false, join-classpath: true }
    MythicMobs: { load: BEFORE, required: false, join-classpath: true }
    CraftEngine: { load: BEFORE, required: false, join-classpath: true }

    # 可选依赖插件
    EnchantmentSlots: { load: BEFORE, required: false, join-classpath: true }
    MythicChanger: { load: BEFORE, required: false, join-classpath: true }
    CustomFishing: { load: BEFORE, required: false, join-classpath: true }
    CustomCrops: { load: BEFORE, required: false, join-classpath: true }