# 配置文件版本, 勿动捏 ~
file-version: 1

# 语言配置, 请确保语言缩写是Locale可识别的, 如 en, zh_CN, zh_TW 等.
language: "zh-CN"

# 数据库
database:
  # 数据库类型
  # (mysql h2)
  type: "h2"
  # MySQL数据库
  mysql:
    # 地址
    host: "127.0.0.1:3306"
    # 数据库
    database: "firenchan"
    # 用户
    user: "root"
    # 密码
    password: "root"
  # H2数据库
  h2:
    # 数据库文件
    file: "database.db"